---
# tasks file for frontend
- name: install httpie and haproxy
  yum:
    name: "{{ packages }}"
    state: latest

- name: enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: true

- name: configure haproxy
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy

